apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: news-portal-replicaset
spec:
  template:
    metadata:
      name: news-portal
      labels:
        app: news-portal
    spec:
      containers:
        - name: news-portal-container
          image: aluracursos/news-portal:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-portal
  replicas: 3
  selector:
    matchLabels:
      app: news-portal