apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: news-system-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: news-system
      name: news-system
    spec:
      containers:
        - name: news-system-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-system-configmap
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mountPath: /tmp
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images-pvc
        - name: session
          persistentVolumeClaim:
            claimName: session-pvc
  selector:
    matchLabels:
      app: news-system
  serviceName: svc-news-system