apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  captacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-disk
  storageClassName: standard